# Generated by Django 4.2.7 on 2025-03-23 05:51

from django.db import migrations
from django.utils.text import slugify


def create_job_categories(apps, schema_editor):
    # Get the Category model
    Category = apps.get_model('jobs', 'Category')
    
    # Define categories from specs/03-job-management.md
    categories = [
        {
            'name': 'Web Development',
            'description': 'Projects related to building and maintaining websites',
            'slug': 'web-development'
        },
        {
            'name': 'Mobile Development',
            'description': 'Projects related to building mobile applications',
            'slug': 'mobile-development'
        },
        {
            'name': 'Design & Creative',
            'description': 'Projects related to design, graphics, and creative work',
            'slug': 'design-creative'
        },
        {
            'name': 'Writing & Translation',
            'description': 'Content creation, writing, and translation projects',
            'slug': 'writing-translation'
        },
        {
            'name': 'Administrative & Support',
            'description': 'Projects related to administrative tasks and support roles',
            'slug': 'administrative-support'
        },
        {
            'name': 'Finance & Accounting',
            'description': 'Projects related to financial services and accounting',
            'slug': 'finance-accounting'
        },
        {
            'name': 'Marketing & Sales',
            'description': 'Projects related to marketing, advertising, and sales',
            'slug': 'marketing-sales'
        },
        {
            'name': 'Legal',
            'description': 'Projects related to legal services and consultation',
            'slug': 'legal'
        },
        {
            'name': 'Engineering & Architecture',
            'description': 'Projects related to engineering and architectural design',
            'slug': 'engineering-architecture'
        },
        {
            'name': 'Other',
            'description': 'Other miscellaneous projects',
            'slug': 'other'
        },
    ]
    
    # Create each category
    for category_data in categories:
        # Check if category already exists
        if not Category.objects.filter(slug=category_data['slug']).exists():
            Category.objects.create(**category_data)


def remove_job_categories(apps, schema_editor):
    # Get the Category model
    Category = apps.get_model('jobs', 'Category')
    
    # Define category slugs to be removed
    category_slugs = [
        'web-development',
        'mobile-development',
        'design-creative',
        'writing-translation',
        'administrative-support',
        'finance-accounting',
        'marketing-sales',
        'legal',
        'engineering-architecture',
        'other',
    ]
    
    # Delete each category
    Category.objects.filter(slug__in=category_slugs).delete()


class Migration(migrations.Migration):

    dependencies = [
        ('jobs', '0001_initial'),
    ]

    operations = [
        migrations.RunPython(create_job_categories, remove_job_categories),
    ]
