version: '3.8'

services:
  web:
    build: .
    command: >
      bash -c "ln -sf /app/freelancer_marketplace/jobs /app/jobs &&
              python manage.py runserver 0.0.0.0:8000"
    volumes:
      - .:/app
    ports:
      - "8000:8000"
    depends_on:
      - db
    environment:
      - DEBUG=1
      - DJANGO_ALLOWED_HOSTS=localhost,127.0.0.1
      - DB_HOST=db
      - DB_NAME=freelancer_marketplace
      - DB_USER=postgres
      - DB_PASSWORD=postgres
      - DB_PORT=5432
  
  db:
    image: postgres:13
    volumes:
      - postgres_data:/var/lib/postgresql/data/
    environment:
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_USER=postgres
      - POSTGRES_DB=freelancer_marketplace
    ports:
      - "5432:5432"

volumes:
  postgres_data: 